name: decampoacampo

services:
  mysql:
    image: mysql:8.0
    container_name: decampoacampo_mysql
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file:
      - ./docker/mysql/mysql.env

  php:
    build: .
    container_name: decampoacampo_php
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PRECIO_USD: 1485.00
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: decampoacampo
      DB_USER: root
      DB_PASS: root